name: gusteau
description: "Recipes App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts:
  flutter_svg:
  flutter_screenutil:
  smooth_page_indicator:
  pin_code_fields:
  easy_stepper:
  flutter_timer_countdown:
#  flutter_facebook_auth:
#  google_sign_in:
#  sign_in_with_apple:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/


